version: '3.1'

services:

  vaccine_api:
    container_name: vaccine_api_container
    build:
      context: .
    image: vaccine_api_image
    restart: always
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://vaccine_mariadb:3306/vaccine
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
    depends_on:
      - vaccine_mariadb

  vaccine_mariadb:
    container_name: vaccine_mariadb_container
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=vaccine
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
